--UPDATING AND DELETING STATEMENTS

USE [SQL B]

SELECT * FROM EmployeeDemographics

--UPDATE STATEMENT IS BASICALLY USED TO UPDATE THE DATA IN THE TABLE AS IN THIS QUERY I UPDATE THE EMPLOYEEID AGE AND GENDER BASED ON CONDITION
UPDATE EmployeeDemographics
SET EmployeeID = 1012
WHERE FirstName = 'Holly' AND LastName = 'Flax'

UPDATE EmployeeDemographics
SET Age = 32 , Gender = 'Female'
WHERE EmployeeID = 1012

--DELETE STATEMENT IS USED TO DELETE THE ROW FROM THE TABLE BASED ON CONDITION USING WHERE CLAUSE
DELETE FROM EmployeeDemographics
WHERE EmployeeID = 1005