--WHERE STATEMENT
--=,<>,<,>.And,Or,Like,Null,Not Null,In

USE [SQL B];

USED TO DISPLAY THE DATA BASED ON CONDITION AS EQUALS TO =
SELECT * FROM EmployeeDemographics
WHERE FirstName = 'jim';

USED TO DISPLAY THE DATA BASED ON CONDITION AS GREATER THAN >
SELECT * FROM EmployeeDemographics
WHERE Age > 30 ;

USED TO DISPLAY THE DATA BASED ON CONDITION AS GREATER THAN EQUALS TO >=
SELECT * FROM EmployeeDemographics
WHERE Age >= 30 ;

USED TO DISPLAY THE DATA BASED ON CONDITION AS LESSER THAN <
SELECT * FROM EmployeeDemographics
WHERE Age < 30 ;

USED TO DISPLAY THE DATA BASED ON CONDITION AND WHERE DISPLAY ONLY WHEN BOTH CONDITION IS TRUE
SELECT * FROM EmployeeDemographics
WHERE Age <= 32  AND Gender = 'Male';

USED TO DISPLAY THE DATA BASED ON CONDITION AND WHERE DISPLAY WHEN ANY ONE CONDITION IS TRUE
SELECT * FROM EmployeeDemographics
WHERE Age <= 32  OR Gender = 'Male';

USED TO DISPLAY THE DATA BASED ON CONDITION LIKE WHERE WE USE % TO FIND DATA BASED ON SOME CHARACTER
SELECT * FROM EmployeeDemographics
WHERE LastName LIKE '%S%n%';

USED TO DISPLAY THE DATA BASED ON CONDITION WHERE DATA IS NULL
SELECT * FROM EmployeeDemographics
WHERE FirstName is NULL;

USED TO DISPLAY THE DATA BASED ON CONDITION WHERE DATA IS NOT NULL
SELECT * FROM EmployeeDemographics
WHERE FirstName is NOT NULL;

USED TO DISPLAY THE DATA BASED ON CONDITION WHERE WE CHECK MULTIPLE COLUMNS IN THE TABLE
SELECT * FROM EmployeeDemographics
WHERE FirstName IN ('jim','Michael');