--HAVING CLAUSE

USE [SQL B]

--HAVING CLAUSE BASICALLY USED WITH GROUP BY STATEMENT AND WE CANT USE AGGREGATE FUNCTION WITH WHERE STATEMENT SO WE HAVE TO USE HAVING CLAUSE STATEMENT FOR THAT PURPOSE
--AS IN THIS QUERY WE GROUP THE DATA BASED ON JOBTITLE AND FIND OUT NUMBER OF JOBS THAT HAVING MORE THAN 1 PERSON OF THAT JOB
SELECT JobTitle,COUNT(JobTitle) AS [NUMBER OF PERSONS IN EACH JOB]
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID = EmployeeSalary.employeeID
GROUP BY JobTitle
HAVING COUNT(JobTitle) > 1

--THIS QUERY BASICALLY USED TO FIND OUT AVERAGE SALARY OF JOBS THAT HAVING MORE THAN 45000 IN THE SALARY TABLE
SELECT JobTitle,AVG(Salary) AS [AVERAGE SALARY]
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID = EmployeeSalary.employeeID
GROUP BY JobTitle
HAVING AVG(Salary) > 45000
ORDER BY AVG(Salary)