-- TOPIC - STRING FUNCTIONS : TRIM , LTRIM , RTRIM , REPLACE , SUBSTRING , UPPER , LOWER

USE [SQL B]

--Drop Table EmployeeErrors;

CREATE TABLE EmployeeErrors (
EmployeeID varchar(50),
FirstName varchar(50),
LastName varchar(50)
)

Insert into EmployeeErrors Values 
('1001  ', 'Jimbo', 'Halbert')
,('  1002', 'Pamela', 'Beasely')
,('1005', 'TOby', 'Flenderson - Fired')

Select *
From EmployeeErrors

-- TRIM // LTRIM // RTRIM
-- TRIM IS BASICALLY USED TO REMOVE UNWANTED SPACE FROM THE STARTING OR ENDING OF THE STRING
SELECT EmployeeID,TRIM(EmployeeID) AS EMPIDTRIM
FROM EmployeeErrors

-- LTRIM IS USED TO REMOVE STARTING SPACE FROM THE STRING
SELECT EmployeeID,LTRIM(EmployeeID) AS EMPIDLTRIM
FROM EmployeeErrors

-- RTRIM IS USED TO REMOVE ENDING UNWANTED SPACE FROM THE STRING
SELECT EmployeeID,RTRIM(EmployeeID) AS EMPIDRTRIM
FROM EmployeeErrors

-- REPLACE
--REPLACE US BASICALLY USED TO REPLACE THE STRING OR CHARACTER IN A ROW COLUMN
SELECT LastName , REPLACE(LastName,'- Fired','') AS  LASTNAMEFIXED
FROM EmployeeErrors

-- SUBSTRING 
-- SUBSTRING IS BASICALLY USED TO DISPLAY SUBSTRING BASED ON ITS RANGE
SELECT SUBSTRING(FirstName,1,3)
FROM EmployeeErrors

-- USED AS A FUZZY LOGIC ALSO
SELECT SUBSTRING(ERR.FirstName,1,3),ERR.FirstName,SUBSTRING(ED.FirstName,1,3),ED.FirstName
FROM EmployeeErrors ERR
JOIN EmployeeDemographics ED
ON SUBSTRING(ERR.FirstName,1,3) = SUBSTRING(ED.FirstName,1,3)

-- LOWER // UPPER
--LOWER IS USED TO LOWER THE STRING'S CHARACTER
SELECT FirstName,LOWER(FirstName)
FROM EmployeeErrors

--UPPER IS USED TO UPPERCASE THE STRING'S CHARACTER
SELECT FirstName,UPPER(FirstName)
FROM EmployeeErrors