--USE CASE STATEMENTS

USE [SQL B];

--CASE STATEMENTS BASICALLY USED AS IF - ELSE STATEMENT AS IN THAT QUERY BASICALLY WE QUERY ON AGE COLUMN TO CREATE ADULTHOOD COLUMN BASED ON CONDITION
SELECT FirstName,LastName,Age, 
CASE
	WHEN AGE=38 THEN 'Stanley'
	WHEN AGE>30 THEN 'Old'
	WHEN AGE BETWEEN 27 AND 30 THEN 'Young'
	ELSE 'Baby'
END AS Adulthood
FROM EmployeeDemographics
WHERE Age IS NOT NULL
ORDER BY AGE

--AS IN THIS QUERY I USE CASE STATEMENT TO INCREASE THE SALARY OF EMPLOYEE BASED ON THEIR JOBTITLE AND DISPLAY THAT COLUMN NAMED AS [SALARY WITH BONUS]
SELECT FirstName,LastName,JobTitle,Salary,
CASE 
	WHEN JobTitle = 'Salesman' THEN Salary+(Salary*0.10)
	WHEN JobTitle = 'Accountant' THEN Salary+(Salary*0.05)
	WHEN JobTitle = 'HR' THEN Salary+(Salary*0.000001)
	ELSE Salary+(Salary*0.3)
END AS [SALARY WITH BONUS]
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID = EmployeeSalary.employeeID
