----GROUP BY AND ORDER BY

--USED TO GROUP DATA BASED ON GENDER COLUMN
--SELECT Gender
--FROM EmployeeDemographics
--GROUP BY Gender

--USED TO GROUP DATA BASED ON GENDER COLUMN AND COUNT DATA BASED ON GENDER
--SELECT Gender,COUNT(Gender) 
--FROM EmployeeDemographics
--GROUP BY Gender

--USED TO GROUP DATA BASED ON MULTIPLE COLUMNS
--SELECT Gender,Age,COUNT(Gender) 
--FROM EmployeeDemographics
--GROUP BY Gender,Age

--USED TO GROUP DATA BASED ON WHERE CONDITION
--SELECT Gender,COUNT(Gender) 
--FROM EmployeeDemographics
--WHERE Age > 31
--GROUP BY Gender

--USED TO GROUP AND ORDER THE DATA IN ASC BY DEFAULT AND DESC ACCORDING TO SPECIFIC COLUMN
--SELECT Gender,COUNT(Gender) AS COUNTGENDER 
--FROM EmployeeDemographics
--WHERE Age > 31
--GROUP BY Gender
--ORDER BY COUNTGENDER

--USED TO GROUPING AND ORDERING DATA BASED ON WHERE CONDITION ON SPECIFIC COLUMN
--SELECT Gender,COUNT(Gender) AS COUNTGENDER 
--FROM EmployeeDemographics
--WHERE Age > 31
--GROUP BY Gender
--ORDER BY COUNTGENDER DESC

--USED TO ORDERING DATA BASED ON COLUMN
--SELECT *
--FROM EmployeeDemographics
--ORDER BY Age

--USED TO ORDERING DATA BASED ON MULTIPLE COLUMN 
--SELECT *
--FROM EmployeeDemographics
--ORDER BY Age,Gender

--USED TO ORDERING DATA BASED ON MULTIPLE COLUMN AND THEIR ORDERING 
--SELECT *
--FROM EmployeeDemographics
--ORDER BY Age,Gender DESC

--USED TO ORDERING DATA BASED ON MULTIPLE COLUMN AND THEIR ORDERING
--SELECT *
--FROM EmployeeDemographics
--ORDER BY Age DESC,Gender DESC

--USED TO ORDER DATA BASED ON COLUMN NUMBER ALSO
--SELECT *
--FROM EmployeeDemographics
--ORDER BY 4 DESC,5 DESC