--Select Statement
--Top, Distinct, Count, As, Max, Min, Avg

--USED TO SELECT WHOLE TABLE
--SELECT * FROM EmployeeDemographics

--USED TO SELECT FIRSTNAME AND LASTNAME OF TABLE
--SELECT FirstName,LastName
--FROM EmployeeDemographics

--USED TO SELECT TOP 5 ROWS OF TABLE
--SELECT TOP 5 * FROM EmployeeDemographics

--USED TO GIVE UNIQUE VALUES FROM TABLE OF SPECIFIC COLUMN
--SELECT DISTINCT(Gender) FROM EmployeeDemographics

--USED TO RETURN THE TOTAL VALUES IN PARTICULAR COLUMN
--SELECT COUNT(LastName)
--FROM EmployeeDemographics

--USED TO RENAME COLUMN NAME TO DESIRED NAME
--SELECT COUNT(LastName) AS LastNameCount FROM EmployeeDemographics

--USED TO RETURN MAXIMUM VALUE FROM PARTICULAR COLUMN
-- SELECT MAX(Salary) FROM EmployeeSalary

--USED TO RETURN MINIMUM VALUE FROM PARTICULAR COLUMN
 --SELECT MIN(Salary) FROM EmployeeSalary

 --USED TO RETURN AVERAGE VALUE FROM PARTICULAR COLUMN
 --SELECT AVG(Salary) FROM EmployeeSalary

 --USED TO ACCESS THE TABLE OF DATABASE FROM ANOTHER DATABASE
 --SELECT * FROM [SQL B].dbo.EmployeeSalary